# Generated by Django 3.0.5 on 2020-04-02 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='lookingFor',
            field=models.CharField(choices=[('internship', 'internship'), ('collaborate on a project', 'collaborate on a project')], max_length=100),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/%Y/%m/%d')),
                ('num_of_employees', models.IntegerField(blank=True, null=True)),
                ('lookingTo', models.CharField(choices=[('hire interns', 'hire interns'), ('hire employees', 'hire employees'), ('both', 'both')], max_length=100)),
                ('videoURL', models.URLField(blank=True, null=True)),
                ('webURL', models.URLField(blank=True, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
